export interface CountryDialCode {
  id: string;
  flag: string;
  code: string;
  country: string;
  region: 'Afrique' | 'Europe' | 'Amérique' | 'Asie' | 'Océanie';
}

export const COUNTRY_CODES: CountryDialCode[] = [
  // --- AFRIQUE (Tous les 54 pays d'Afrique) ---
  { id: 'cd', flag: '🇨🇩', code: '+243', country: 'RD Congo', region: 'Afrique' },
  { id: 'cg', flag: '🇨🇬', code: '+242', country: 'Congo-Brazzaville', region: 'Afrique' },
  { id: 'rw', flag: '🇷🇼', code: '+250', country: 'Rwanda', region: 'Afrique' },
  { id: 'bi', flag: '🇧🇮', code: '+257', country: 'Burundi', region: 'Afrique' },
  { id: 'ug', flag: '🇺🇬', code: '+256', country: 'Ouganda', region: 'Afrique' },
  { id: 'tz', flag: '🇹🇿', code: '+255', country: 'Tanzanie', region: 'Afrique' },
  { id: 'ke', flag: '🇰🇪', code: '+254', country: 'Kenya', region: 'Afrique' },
  { id: 'ao', flag: '🇦🇴', code: '+244', country: 'Angola', region: 'Afrique' },
  { id: 'cm', flag: '🇨🇲', code: '+237', country: 'Cameroun', region: 'Afrique' },
  { id: 'ci', flag: '🇨🇮', code: '+225', country: 'Côte d’Ivoire', region: 'Afrique' },
  { id: 'sn', flag: '🇸🇳', code: '+221', country: 'Sénégal', region: 'Afrique' },
  { id: 'ga', flag: '🇬🇦', code: '+241', country: 'Gabon', region: 'Afrique' },
  { id: 'cf', flag: '🇨🇫', code: '+236', country: 'Centrafrique', region: 'Afrique' },
  { id: 'td', flag: '🇹🇩', code: '+235', country: 'Tchad', region: 'Afrique' },
  { id: 'gq', flag: '🇬🇶', code: '+240', country: 'Guinée Équatoriale', region: 'Afrique' },
  { id: 'st', flag: '🇸🇹', code: '+239', country: 'Sao Tomé-et-Principe', region: 'Afrique' },
  { id: 'ng', flag: '🇳🇬', code: '+234', country: 'Nigeria', region: 'Afrique' },
  { id: 'gh', flag: '🇬🇭', code: '+233', country: 'Ghana', region: 'Afrique' },
  { id: 'bj', flag: '🇧🇯', code: '+229', country: 'Bénin', region: 'Afrique' },
  { id: 'tg', flag: '🇹🇬', code: '+228', country: 'Togo', region: 'Afrique' },
  { id: 'ml', flag: '🇲🇱', code: '+223', country: 'Mali', region: 'Afrique' },
  { id: 'gn', flag: '🇬🇳', code: '+224', country: 'Guinée', region: 'Afrique' },
  { id: 'bf', flag: '🇧🇫', code: '+226', country: 'Burkina Faso', region: 'Afrique' },
  { id: 'ne', flag: '🇳🇪', code: '+227', country: 'Niger', region: 'Afrique' },
  { id: 'mr', flag: '🇲🇷', code: '+222', country: 'Mauritanie', region: 'Afrique' },
  { id: 'gw', flag: '🇬🇼', code: '+245', country: 'Guinée-Bissau', region: 'Afrique' },
  { id: 'sl', flag: '🇸🇱', code: '+232', country: 'Sierra Leone', region: 'Afrique' },
  { id: 'lr', flag: '🇱🇷', code: '+231', country: 'Libéria', region: 'Afrique' },
  { id: 'gm', flag: '🇬🇲', code: '+220', country: 'Gambie', region: 'Afrique' },
  { id: 'cv', flag: '🇨🇻', code: '+238', country: 'Cap-Vert', region: 'Afrique' },
  { id: 'ma', flag: '🇲🇦', code: '+212', country: 'Maroc', region: 'Afrique' },
  { id: 'dz', flag: '🇩🇿', code: '+213', country: 'Algérie', region: 'Afrique' },
  { id: 'tn', flag: '🇹🇳', code: '+216', country: 'Tunisie', region: 'Afrique' },
  { id: 'eg', flag: '🇪🇬', code: '+20', country: 'Égypte', region: 'Afrique' },
  { id: 'ly', flag: '🇱🇾', code: '+218', country: 'Libye', region: 'Afrique' },
  { id: 'sd', flag: '🇸🇩', code: '+249', country: 'Soudan', region: 'Afrique' },
  { id: 'ss', flag: '🇸🇸', code: '+211', country: 'Soudan du Sud', region: 'Afrique' },
  { id: 'et', flag: '🇪🇹', code: '+251', country: 'Éthiopie', region: 'Afrique' },
  { id: 'er', flag: '🇪🇷', code: '+291', country: 'Érythrée', region: 'Afrique' },
  { id: 'dj', flag: '🇩🇯', code: '+253', country: 'Djibouti', region: 'Afrique' },
  { id: 'so', flag: '🇸🇴', code: '+252', country: 'Somalie', region: 'Afrique' },
  { id: 'za', flag: '🇿🇦', code: '+27', country: 'Afrique du Sud', region: 'Afrique' },
  { id: 'zm', flag: '🇿🇲', code: '+260', country: 'Zambie', region: 'Afrique' },
  { id: 'zw', flag: '🇿🇼', code: '+263', country: 'Zimbabwe', region: 'Afrique' },
  { id: 'mg', flag: '🇲🇬', code: '+261', country: 'Madagascar', region: 'Afrique' },
  { id: 'mz', flag: '🇲🇿', code: '+258', country: 'Mozambique', region: 'Afrique' },
  { id: 'mw', flag: '🇲🇼', code: '+265', country: 'Malawi', region: 'Afrique' },
  { id: 'na', flag: '🇳🇦', code: '+264', country: 'Namibie', region: 'Afrique' },
  { id: 'bw', flag: '🇧🇼', code: '+267', country: 'Botswana', region: 'Afrique' },
  { id: 'ls', flag: '🇱🇸', code: '+266', country: 'Lesotho', region: 'Afrique' },
  { id: 'sz', flag: '🇸🇿', code: '+268', country: 'Eswatini', region: 'Afrique' },
  { id: 'mu', flag: '🇲🇺', code: '+230', country: 'Maurice', region: 'Afrique' },
  { id: 'sc', flag: '🇸🇨', code: '+248', country: 'Seychelles', region: 'Afrique' },
  { id: 'km', flag: '🇰🇲', code: '+269', country: 'Comores', region: 'Afrique' },

  // --- EUROPE ---
  { id: 'fr', flag: '🇫🇷', code: '+33', country: 'France', region: 'Europe' },
  { id: 'be', flag: '🇧🇪', code: '+32', country: 'Belgique', region: 'Europe' },
  { id: 'ch', flag: '🇨🇭', code: '+41', country: 'Suisse', region: 'Europe' },
  { id: 'gb', flag: '🇬🇧', code: '+44', country: 'Royaume-Uni', region: 'Europe' },
  { id: 'de', flag: '🇩🇪', code: '+49', country: 'Allemagne', region: 'Europe' },
  { id: 'es', flag: '🇪🇸', code: '+34', country: 'Espagne', region: 'Europe' },
  { id: 'it', flag: '🇮🇹', code: '+39', country: 'Italie', region: 'Europe' },
  { id: 'pt', flag: '🇵🇹', code: '+351', country: 'Portugal', region: 'Europe' },
  { id: 'nl', flag: '🇳🇱', code: '+31', country: 'Pays-Bas', region: 'Europe' },
  { id: 'se', flag: '🇸🇪', code: '+46', country: 'Suède', region: 'Europe' },
  { id: 'no', flag: '🇳🇴', code: '+47', country: 'Norvège', region: 'Europe' },
  { id: 'ru', flag: '🇷🇺', code: '+7', country: 'Russie', region: 'Europe' },
  { id: 'tr', flag: '🇹🇷', code: '+90', country: 'Turquie', region: 'Europe' },
  { id: 'ua', flag: '🇺🇦', code: '+380', country: 'Ukraine', region: 'Europe' },
  { id: 'pl', flag: '🇵🇱', code: '+48', country: 'Pologne', region: 'Europe' },

  // --- AMÉRIQUE ---
  { id: 'us', flag: '🇺🇸', code: '+1', country: 'États-Unis', region: 'Amérique' },
  { id: 'ca', flag: '🇨🇦', code: '+1', country: 'Canada', region: 'Amérique' },
  { id: 'br', flag: '🇧🇷', code: '+55', country: 'Brésil', region: 'Amérique' },
  { id: 'mx', flag: '🇲🇽', code: '+52', country: 'Mexique', region: 'Amérique' },
  { id: 'ar', flag: '🇦🇷', code: '+54', country: 'Argentine', region: 'Amérique' },
  { id: 'co', flag: '🇨🇴', code: '+57', country: 'Colombie', region: 'Amérique' },
  { id: 'cl', flag: '🇨🇱', code: '+56', country: 'Chili', region: 'Amérique' },
  { id: 'pe', flag: '🇵🇪', code: '+51', country: 'Pérou', region: 'Amérique' },
  { id: 'ht', flag: '🇭🇹', code: '+509', country: 'Haïti', region: 'Amérique' },

  // --- ASIE ---
  { id: 'cn', flag: '🇨🇳', code: '+86', country: 'Chine', region: 'Asie' },
  { id: 'jp', flag: '🇯🇵', code: '+81', country: 'Japon', region: 'Asie' },
  { id: 'in', flag: '🇮🇳', code: '+91', country: 'Inde', region: 'Asie' },
  { id: 'kr', flag: '🇰🇷', code: '+82', country: 'Corée du Sud', region: 'Asie' },
  { id: 'ae', flag: '🇦🇪', code: '+971', country: 'Émirats Arabes Unis', region: 'Asie' },
  { id: 'sa', flag: '🇸🇦', code: '+966', country: 'Arabie Saoudite', region: 'Asie' },
  { id: 'qa', flag: '🇶🇦', code: '+974', country: 'Qatar', region: 'Asie' },
  { id: 'il', flag: '🇮🇱', code: '+972', country: 'Israël', region: 'Asie' },
  { id: 'lb', flag: '🇱🇧', code: '+961', country: 'Liban', region: 'Asie' },
  { id: 'id', flag: '🇮🇩', code: '+62', country: 'Indonésie', region: 'Asie' },
  { id: 'vn', flag: '🇻🇳', code: '+84', country: 'Vietnam', region: 'Asie' },
  { id: 'ph', flag: '🇵🇭', code: '+63', country: 'Philippines', region: 'Asie' },
  { id: 'sg', flag: '🇸🇬', code: '+65', country: 'Singapour', region: 'Asie' },
  { id: 'my', flag: '🇲🇾', code: '+60', country: 'Malaisie', region: 'Asie' },

  // --- OCÉANIE ---
  { id: 'au', flag: '🇦🇺', code: '+61', country: 'Australie', region: 'Océanie' },
  { id: 'nz', flag: '🇳🇿', code: '+64', country: 'Nouvelle-Zélande', region: 'Océanie' },
];
